Fix repeated api calls
1058-Sophia-Gavrila-Forge/Portfolio-Frontend pull request #26
Opened 2021-07-31 00:59 UTC by ajang06

Found and fixed a minor bug where repeated api calls were happening

2021-07-31 01:02 UTC, ddinh submitted a review, later dismissed

2021-07-31 16:48 UTC, sophiagavrila requested changes
@ajang06 @JakeGeiser @ddinh  SonarCloud doesn't like [this function, `requestSort()`](https://sonarcloud.io/project/issues?id=1058-Sophia-Gavrila-Forge_Portfolio-Frontend&pullRequest=26&resolved=false&types=CODE_SMELL) because it's over 15 lines long.  

Could you try refactoring requestSort() by either adjusting the logic within the function or breaking it into separate functions which you call within it?

EDIT: _This is for Monday! No need to work on the weekend, just sending premptive notifs for Monday_

2021-08-02 02:31 UTC, FBThornton approved these changes
Good simplification of the sorting method.

2021-08-02 13:28 UTC, sophiagavrila approved these changes

2021-08-02 13:28 UTC, merged